### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by tjpugh** [pughlab/ConsensusCruncher#22]
ConsensusCruncher silently runs out of memory mid-bam file and makes SSCS and DCS bam files that only contain reads mapping to the alphanumerically-first chromosomes. Could a solution be to only read individual chromosomes from the bam for ConsensusCrunch'ing and then clear the memory before moving on to the next chromosome?

**Comment by jinfengzou-uhn** [comment]
ConsensusCruncher runs on a bed file for both SSCS and DCS. The default bed file is a cytoband file, which is composed of multiple regions for a chromosome. If it is used, then it means the memory is not enough for running on one region (or chromosome if the bed file includes only chromosomes). So, the solution could be preparing the bed file by splitting the chromosome into smaller regions, especially when the sequencing depth is high and memory cannot be enough.
