### ISSUE TITLE
support variable spacer sequences

### ISSUE THREAD

**Issue by drmjc** [pughlab/ConsensusCruncher#23]
**Is your feature request related to a problem? Please describe.**
I'm analysing libraries that have 5bp UMIs followed by a random 2bp spacer that doesn't have to end in T, whereas I think ConsensusCruncher only supports UMI's with known/fixed spacer sequences that must end in T.

**Describe the solution you'd like**
I'd like to be able to provide `bpattern=NNNNNSS`, so that NNNNN is read as the UMI, and SS is skipped as the random spacer. The blist would be a file with all of the 5bp UMI sequences in it (as currently supported).

**Describe alternatives you've considered**
`fgbio` supports a read structure of `5M2S+T` (5bp UMI matches, 2 bp spacer, remaining bp template) to do this job, but fgbio doesn't rescue singleton reads.

**Comment by arnavaz** [comment]
Hello!
Thanks for submitting this issue. We do not support UMIs with variable spacers. However, as an alternative, as you have also figured out, fgbio and UMI-tools will be helpful to extract the UMIs you have. And after barcode extraction, you can use Consensus Cruncher on "consensus" mode to take advantage of the singleton rescue and consensus making. You can use aligner from UMI-tools or bwa (http://bio-bwa.sourceforge.net/) aligner beforehand to get the bam files and then put them through the consensus mode in Consensus Cruncher.
Hope this helps,
Arnavaz

**Comment by drmjc** [comment]
ok, will do thanks.
